import { ApplicationCommandOptionType } from "discord-api-types/v10";
import {
  Client,
  container,
  RegisterCommand,
  type Command as FrameworkCommand,
  type CommandStore,
} from "@wolfstar/http-framework";
import { createTestHarness, makeCommand } from "@wolfstar/http-framework-test-utils";
import { afterEach, describe, expect, test } from "vitest";
import { clearSubcommandRegistries, Command, RegisterAsSubcommand, Subcommand } from "../src/index";
import { SubcommandsAdvancedLoaderStrategy } from "../src/lib/utils/strategy";
import subcommandsPlugin from "../src/plugin";

const base = { discordPublicKey: "a".repeat(64), discordToken: "token" };

function createClient(options: ConstructorParameters<typeof Client>[0]): Client {
  return new Client(options);
}

function commandStrategy(): unknown {
  return (container.stores.get("commands") as CommandStore).strategy;
}

describe("subcommandsAdvancedPlugin", () => {
  test("GIVEN the factory THEN the plugin is named", () => {
    expect((subcommandsPlugin() as { name: string }).name).toBe(
      "@wolfstar/plugin-subcommands-advanced",
    );
  });

  test("GIVEN a client THEN the commands store uses the advanced loader strategy", () => {
    createClient({ ...base, plugins: [subcommandsPlugin()] });

    expect(commandStrategy()).toBeInstanceOf(SubcommandsAdvancedLoaderStrategy);
  });
});

describe("subcommandsAdvancedPlugin loading", () => {
  afterEach(() => clearSubcommandRegistries());

  test("GIVEN the installed strategy WHEN a parent loads THEN its registered children are wired on", async () => {
    @RegisterCommand({ name: "utils", description: "Utility commands" })
    class UtilsCommand extends Subcommand {}

    @RegisterAsSubcommand("utils", (builder) => builder.setName("ping").setDescription("Ping"))
    class PingCommand extends Command {
      public override chatInputRun(interaction: Command.ChatInputInteraction) {
        return interaction.reply({ content: "Pong" });
      }
    }

    createTestHarness({ subcommandsAdvanced: { nameCommandsAutogenerated: true } });
    createClient({ ...base, plugins: [subcommandsPlugin()] });
    const store = container.stores.get("commands") as CommandStore;

    makeCommand(PingCommand);
    const parent = makeCommand(UtilsCommand) as FrameworkCommand;
    await (store.strategy as SubcommandsAdvancedLoaderStrategy).onLoad(store, parent);

    expect(
      parent.router.routeChatInputInteraction({
        id: "0",
        name: "utils",
        type: 1,
        options: [{ type: ApplicationCommandOptionType.Subcommand, name: "ping", options: [] }],
      } as never),
    ).toBe("__wolfstar_sc_ping");
  });
});

describe("register parity", () => {
  afterEach(() => {
    // Whatever strategy the previous client installed must not leak into the next test.
    Object.defineProperty(container.stores.get("commands"), "strategy", {
      value: undefined,
      configurable: true,
      enumerable: true,
      writable: true,
    });
  });

  test("GIVEN the plugin and the register entrypoint THEN they install the same kind of strategy", async () => {
    // First the plugin alone: nothing has imported `./register` yet in this file.
    createClient({ ...base, plugins: [subcommandsPlugin()] });
    const store = container.stores.get("commands") as CommandStore;
    const viaPlugin = Object.getOwnPropertyDescriptor(store, "strategy")!;
    expect(viaPlugin.value).toBeInstanceOf(SubcommandsAdvancedLoaderStrategy);

    Object.defineProperty(store, "strategy", { ...viaPlugin, value: undefined });

    // Then the legacy hook, which registers itself globally on import and applies to every later client.
    await import("../src/register");
    createClient(base);
    const viaRegister = Object.getOwnPropertyDescriptor(store, "strategy")!;

    expect(viaRegister.value).toBeInstanceOf(SubcommandsAdvancedLoaderStrategy);
    expect(viaRegister.value).not.toBe(viaPlugin.value);
    expect({ ...viaRegister, value: undefined }).toEqual({ ...viaPlugin, value: undefined });
  });
});
