import { ApplicationCommandOptionType, InteractionResponseType } from "discord-api-types/v10";
import { container, RegisterCommand } from "@wolfstar/http-framework";
import {
  ChatInputApplicationCommandInteractionData,
  createTestHarness,
  makeCommand,
} from "@wolfstar/http-framework-test-utils";
import {
  clearSubcommandRegistries,
  Command,
  RegisterAsSubcommand,
  RegisterAsSubcommandGroup,
  Subcommand,
  subCommandsRegistry,
  wireParentSubcommands,
} from "../src/index.js";
import "../src/register.js";

async function loadParentAndChildren(
  parent: ReturnType<typeof makeCommand>,
  children: ReturnType<typeof makeCommand>[],
) {
  const store = container.stores.get("commands");
  await store.unloadAll();

  for (const child of children) {
    store.set(child.name, child);
  }

  wireParentSubcommands(parent);
  store.set(parent.name, parent);
  if (parent.router.chatInputName) {
    store.router.addChatInputMapping(parent.router.chatInputName, parent);
  }
}

describe("plugin-subcommands-advanced", () => {
  afterEach(async () => {
    clearSubcommandRegistries();
    await container.stores.get("commands").unloadAll();
  });

  it("wires a modular subcommand onto the parent and runs the child chatInputRun", async () => {
    @RegisterCommand({ name: "utils", description: "Utility commands" })
    class UtilsCommand extends Subcommand {}

    @RegisterAsSubcommand("utils", (builder) =>
      builder.setName("ping").setDescription("Ping the bot"),
    )
    class PingCommand extends Command {
      public override chatInputRun(interaction: Command.ChatInputInteraction) {
        return interaction.reply({ content: "Pong from child!" });
      }
    }

    const { runner } = createTestHarness({
      subcommandsAdvanced: { nameCommandsAutogenerated: true },
    });

    const ping = makeCommand(PingCommand);
    const parent = makeCommand(UtilsCommand);
    await loadParentAndChildren(parent, [ping]);

    expect(subCommandsRegistry.get("utils")?.has("ping")).toBe(true);
    expect(
      parent.router.routeChatInputInteraction({
        id: "0",
        name: "utils",
        type: 1,
        options: [{ type: ApplicationCommandOptionType.Subcommand, name: "ping", options: [] }],
      } as never),
    ).toBe("__wolfstar_sc_ping");

    const result = await runner.run({
      ...ChatInputApplicationCommandInteractionData,
      data: {
        id: "0",
        name: "utils",
        type: 1,
        options: [{ type: ApplicationCommandOptionType.Subcommand, name: "ping", options: [] }],
      },
    });

    expect(result.statusCode).toBe(200);
    expect(result.json()).toMatchObject({
      type: InteractionResponseType.ChannelMessageWithSource,
      data: { content: "Pong from child!" },
    });
  });

  it("wires a grouped modular subcommand", async () => {
    @RegisterCommand((builder) =>
      builder
        .setName("utils")
        .setDescription("Utility commands")
        .addSubcommandGroup((group) => group.setName("poll").setDescription("Poll tools")),
    )
    class UtilsCommand extends Subcommand {}

    @RegisterAsSubcommandGroup("utils", "poll", (builder) =>
      builder.setName("create").setDescription("Create a poll"),
    )
    class PollCreateCommand extends Command {
      public override chatInputRun(interaction: Command.ChatInputInteraction) {
        return interaction.reply({ content: "Poll created!" });
      }
    }

    const { runner } = createTestHarness({
      subcommandsAdvanced: { nameCommandsAutogenerated: true },
    });

    const create = makeCommand(PollCreateCommand);
    const parent = makeCommand(UtilsCommand);
    await loadParentAndChildren(parent, [create]);

    const result = await runner.run({
      ...ChatInputApplicationCommandInteractionData,
      data: {
        id: "0",
        name: "utils",
        type: 1,
        options: [
          {
            type: ApplicationCommandOptionType.SubcommandGroup,
            name: "poll",
            options: [
              { type: ApplicationCommandOptionType.Subcommand, name: "create", options: [] },
            ],
          },
        ],
      },
    });

    expect(result.statusCode).toBe(200);
    expect(result.json()).toMatchObject({
      type: InteractionResponseType.ChannelMessageWithSource,
      data: { content: "Poll created!" },
    });
  });

  it("supports registerSubCommand constructor options", async () => {
    @RegisterCommand({ name: "tools", description: "Tools" })
    class ToolsCommand extends Subcommand {}

    class EchoCommand extends Command {
      public constructor(context: Command.LoaderContext, options: Command.Options) {
        super(context, {
          ...options,
          registerSubCommand: {
            parentCommandName: "tools",
            slashSubcommand: (builder) => builder.setName("echo").setDescription("Echo"),
          },
        });
      }

      public override chatInputRun(interaction: Command.ChatInputInteraction) {
        return interaction.reply({ content: "echo" });
      }
    }

    const { runner } = createTestHarness();
    const echo = makeCommand(EchoCommand);
    const parent = makeCommand(ToolsCommand);
    await loadParentAndChildren(parent, [echo]);

    const result = await runner.run({
      ...ChatInputApplicationCommandInteractionData,
      data: {
        id: "0",
        name: "tools",
        type: 1,
        options: [{ type: ApplicationCommandOptionType.Subcommand, name: "echo", options: [] }],
      },
    });

    expect(result.statusCode).toBe(200);
    expect(result.json()).toMatchObject({
      data: { content: "echo" },
    });
  });
});
