packages:plugin-api:
  - changed-files:
      - any-glob-to-any-file:
          - packages/plugin-api/*
          - packages/plugin-api/**/*
packages:plugin-cache:
  - changed-files:
      - any-glob-to-any-file:
          - packages/plugin-cache/*
          - packages/plugin-cache/**/*
packages:plugin-gateway:
  - changed-files:
      - any-glob-to-any-file:
          - packages/plugin-gateway/*
          - packages/plugin-gateway/**/*
packages:plugin-i18next:
  - changed-files:
      - any-glob-to-any-file:
          - packages/plugin-i18next/*
          - packages/plugin-i18next/**/*
packages:plugin-logger:
  - changed-files:
      - any-glob-to-any-file:
          - packages/plugin-logger/*
          - packages/plugin-logger/**/*
