packages:
  - "packages/*"
allowBuilds:
  "@swc/core": true
  esbuild: true
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - "@wolfstar/http-framework@3.4.0 || 6.1.0 || 6.2.2"
  - "@wolfstar/cli@2.2.0 || 2.6.0"
  - "@wolfstar/kit@0.1.0 || 0.2.0"
  - "@wolfstar/nitro-server@0.2.5 || 0.2.9"
  - "@wolfstar/schema@0.9.0"
  - "@wolfstar/vite-server@0.4.4"
