import {
  applicationCommandRegistry,
  Command as FrameworkCommand,
  container,
} from "@wolfstar/http-framework";
import {
  analyzeSubCommandParsed,
  analyzeSubcommandGroupParsed,
  parseSlashSubcommand,
} from "./functions.js";
import type { SlashSubcommandResolvable } from "./types.js";

type CommandConstructor = new (...args: any[]) => FrameworkCommand;

/**
 * Class decorator that registers the decorated command as a direct subcommand of `parentCommandName`.
 *
 * @example
 * ```typescript
 * import { Command, RegisterAsSubcommand } from '@wolfstar/plugin-subcommands-advanced';
 *
 * @RegisterAsSubcommand('utils', (builder) => builder.setName('ping').setDescription('Ping!'))
 * export class PingCommand extends Command {
 *   public override chatInputRun(interaction: Command.ChatInputInteraction) {
 *     return interaction.reply({ content: 'Pong!' });
 *   }
 * }
 * ```
 */
export function RegisterAsSubcommand(
  parentCommandName: string,
  slashSubcommand: SlashSubcommandResolvable,
) {
  return function decorate<T extends CommandConstructor>(target: T): T {
    const decorated = class extends target {
      public constructor(...args: any[]) {
        const [context, baseOptions = {}] = args as [
          FrameworkCommand.LoaderContext,
          FrameworkCommand.Options,
        ];
        const parsed = parseSlashSubcommand(slashSubcommand);
        const name =
          container.client?.options.subcommandsAdvanced?.nameCommandsAutogenerated === true
            ? `${parentCommandName}/${parsed.name}`
            : baseOptions.name;

        super(context, { ...baseOptions, name });
        analyzeSubCommandParsed(this, parentCommandName, slashSubcommand);
      }
    } as T;

    applicationCommandRegistry.ensure(decorated as unknown as typeof FrameworkCommand);

    return decorated;
  };
}

/**
 * Class decorator that registers the decorated command as a subcommand inside a group.
 *
 * @example
 * ```typescript
 * import { Command, RegisterAsSubcommandGroup } from '@wolfstar/plugin-subcommands-advanced';
 *
 * @RegisterAsSubcommandGroup('utils', 'poll', (builder) =>
 *   builder.setName('create').setDescription('Create a poll')
 * )
 * export class PollCreateCommand extends Command {
 *   public override chatInputRun(interaction: Command.ChatInputInteraction) {
 *     return interaction.reply({ content: 'Created!' });
 *   }
 * }
 * ```
 */
export function RegisterAsSubcommandGroup(
  parentCommandName: string,
  groupName: string,
  slashSubcommand: SlashSubcommandResolvable,
) {
  return function decorate<T extends CommandConstructor>(target: T): T {
    const decorated = class extends target {
      public constructor(...args: any[]) {
        const [context, baseOptions = {}] = args as [
          FrameworkCommand.LoaderContext,
          FrameworkCommand.Options,
        ];
        const parsed = parseSlashSubcommand(slashSubcommand);
        const name =
          container.client?.options.subcommandsAdvanced?.nameCommandsAutogenerated === true
            ? `${parentCommandName}/${groupName}/${parsed.name}`
            : baseOptions.name;

        super(context, { ...baseOptions, name });
        analyzeSubcommandGroupParsed(this, parentCommandName, groupName, slashSubcommand);
      }
    } as T;

    applicationCommandRegistry.ensure(decorated as unknown as typeof FrameworkCommand);

    return decorated;
  };
}
