import { SlashCommandSubcommandBuilder } from "@discordjs/builders";
import { Collection } from "@discordjs/collection";
import { container, type Command } from "@wolfstar/http-framework";
import type { SlashSubcommandResolvable, SubcommandMappingCollection } from "./types.js";

/**
 * Registry of direct subcommands keyed by parent command name, then subcommand name.
 */
export const subCommandsRegistry: Collection<
  string,
  Collection<string, SubcommandMappingCollection>
> = new Collection();

/**
 * Registry of grouped subcommands keyed by parent → group → subcommand name.
 */
export const subCommandsGroupRegistry: Collection<
  string,
  Collection<string, Collection<string, SubcommandMappingCollection>>
> = new Collection();

interface DeferredSubcommand {
  parentCommandName: string;
  groupName?: string;
  slashSubcommand: SlashSubcommandResolvable;
  nameCommandsAutogenerated: boolean;
}

const deferredSubcommands = new Map<Command, DeferredSubcommand[]>();

/**
 * Normalize slash subcommand input into a builder.
 */
export function parseSlashSubcommand(
  subcommand: SlashSubcommandResolvable,
): SlashCommandSubcommandBuilder {
  if (typeof subcommand === "function") {
    const builder = new SlashCommandSubcommandBuilder();
    return subcommand(builder, container) ?? builder;
  }

  if (subcommand instanceof SlashCommandSubcommandBuilder) {
    return subcommand;
  }

  if (
    typeof subcommand === "object" &&
    subcommand !== null &&
    "toJSON" in subcommand &&
    typeof subcommand.toJSON === "function"
  ) {
    const json = (subcommand as { toJSON: () => { name: string; description: string } }).toJSON();
    return new SlashCommandSubcommandBuilder().setName(json.name).setDescription(json.description);
  }

  const data = subcommand as { name: string; description: string };
  return new SlashCommandSubcommandBuilder().setName(data.name).setDescription(data.description);
}

/**
 * Defer parsing a subcommand until the command store starts inserting pieces.
 *
 * Sapphire constructs every piece before inserting any of them during `loadAll`.
 * Keeping the builder callback untouched here prevents it from observing partially
 * initialized services during piece construction.
 *
 * @internal
 */
export function deferSubcommand(
  piece: Command,
  parentCommandName: string,
  slashSubcommand: SlashSubcommandResolvable,
  nameCommandsAutogenerated: boolean,
  groupName?: string,
): void {
  const deferred = {
    parentCommandName,
    groupName,
    slashSubcommand,
    nameCommandsAutogenerated,
  };
  const registrations = deferredSubcommands.get(piece);
  if (registrations) registrations.push(deferred);
  else deferredSubcommands.set(piece, [deferred]);
}

/** @internal */
export function resolveDeferredSubcommands(): void {
  for (const [piece, registrations] of deferredSubcommands) {
    const resolved = registrations.map((deferred) => ({
      deferred,
      parsed: parseSlashSubcommand(deferred.slashSubcommand),
    }));

    for (const { deferred, parsed } of resolved) {
      if (deferred.nameCommandsAutogenerated) {
        Object.defineProperty(piece, "name", {
          configurable: true,
          enumerable: true,
          writable: true,
          value: deferred.groupName
            ? `${deferred.parentCommandName}/${deferred.groupName}/${parsed.name}`
            : `${deferred.parentCommandName}/${parsed.name}`,
        });
      }

      registerParsedSubcommand(piece, deferred.parentCommandName, parsed, deferred.groupName);
    }

    deferredSubcommands.delete(piece);
  }
}

/** @internal */
export function clearDeferredSubcommands(): void {
  deferredSubcommands.clear();
}

/**
 * Stable method name linked on the parent command for a direct subcommand.
 */
export function subcommandMethodName(subcommandName: string): string {
  return `__wolfstar_sc_${subcommandName}`;
}

/**
 * Stable method name linked on the parent command for a grouped subcommand.
 */
export function subcommandGroupMethodName(groupName: string, subcommandName: string): string {
  return `__wolfstar_sc_${groupName}_${subcommandName}`;
}

/**
 * Register a command piece as a direct subcommand of `parentCommandName`.
 */
export function analyzeSubCommandParsed(
  piece: Command,
  parentCommandName: string,
  subcommand: SlashSubcommandResolvable,
): Command {
  const subcommandParsed = parseSlashSubcommand(subcommand);
  registerParsedSubcommand(piece, parentCommandName, subcommandParsed);

  return piece;
}

/**
 * Register a command piece as a subcommand inside a group of `parentCommandName`.
 */
export function analyzeSubcommandGroupParsed(
  piece: Command,
  parentCommandName: string,
  groupName: string,
  subcommand: SlashSubcommandResolvable,
): Command {
  const subcommandParsed = parseSlashSubcommand(subcommand);
  registerParsedSubcommand(piece, parentCommandName, subcommandParsed, groupName);

  return piece;
}

function registerParsedSubcommand(
  piece: Command,
  parentCommandName: string,
  subcommandParsed: SlashCommandSubcommandBuilder,
  groupName?: string,
): void {
  const subcommandName = subcommandParsed.name;
  const methodName = groupName
    ? subcommandGroupMethodName(groupName, subcommandName)
    : subcommandMethodName(subcommandName);
  const entry: SubcommandMappingCollection = {
    slashCommand: subcommandParsed,
    commandPiece: piece,
    methodName,
  };

  if (!groupName) {
    const registry = subCommandsRegistry.ensure(parentCommandName, () => new Collection());
    registry.set(subcommandName, entry);
    return;
  }

  const parentRegistry = subCommandsGroupRegistry.ensure(parentCommandName, () => new Collection());
  const groupRegistry = parentRegistry.ensure(groupName, () => new Collection());
  groupRegistry.set(subcommandName, entry);
}
