import type { SlashCommandSubcommandBuilder } from "@discordjs/builders";
import type { APIApplicationCommandSubcommandOption } from "discord-api-types/v10";
import type { container, Command } from "@wolfstar/http-framework";

/**
 * Resolvable slash-subcommand payload accepted by the plugin.
 */
export type SlashSubcommandResolvable =
  | SlashCommandSubcommandBuilder
  | { toJSON(): Pick<APIApplicationCommandSubcommandOption, "name" | "description"> }
  | Pick<APIApplicationCommandSubcommandOption, "name" | "description">
  | ((
      builder: SlashCommandSubcommandBuilder,
      Container: typeof container,
    ) => SlashCommandSubcommandBuilder | void);

/**
 * Options to register a command class as a subcommand of a parent command.
 */
export interface RegisterSubCommandOptions {
  /**
   * The chat-input name of the parent command (the name passed to {@link RegisterCommand}).
   */
  parentCommandName: string;
  /**
   * Slash subcommand data (builder, JSON, or callback). Required for Discord registration.
   */
  slashSubcommand: SlashSubcommandResolvable;
}

/**
 * Options to register a command class as a subcommand inside a parent subcommand group.
 */
export interface RegisterSubCommandGroupOptions {
  /**
   * The chat-input name of the parent command.
   */
  parentCommandName: string;
  /**
   * The name of the subcommand group already registered on the parent.
   */
  groupName: string;
  /**
   * Slash subcommand data (builder, JSON, or callback). Required for Discord registration.
   */
  slashSubcommand: SlashSubcommandResolvable;
}

/**
 * Extra {@link Command} options accepted by the advanced subcommands {@link Command} class.
 */
export interface SubcommandCommandOptions {
  registerSubCommand?: RegisterSubCommandOptions;
  registerSubcommandInGroup?: RegisterSubCommandGroupOptions;
}

/**
 * Entry stored in the subcommand / group registries.
 */
export interface SubcommandMappingCollection {
  slashCommand: SlashCommandSubcommandBuilder;
  commandPiece: Command;
  methodName: string;
}

/**
 * Plugin options under `ClientOptions.subcommandsAdvanced`.
 */
export interface PluginSubcommandOptions {
  /**
   * Auto-generate piece names as `parent/sub` or `parent/group/sub` so multiple
   * subcommand classes do not collide in `@sapphire/pieces`.
   *
   * @default false
   */
  nameCommandsAutogenerated?: boolean;
}
