// This file is automatically generated, do not edit it.
/* eslint-disable */
/* oxlint-disable */
// oxfmt-ignore
// prettier-ignore
import "i18next";

// oxfmt-ignore
// prettier-ignore
declare module "i18next" {
  interface CustomTypeOptions {
    resources: {
      "commands/ping": {
        name: "ping";
        nameName: "ping";
        nameDescription: "Checks whether the bot is alive";
        success: "Pong!";
        successWithLatency: "Pong! Took me {{latency}}ms to reply";
      };
      default: {
        default: "Missing key: {{key}}";
      };
    } & CustomResources;
  }

  interface CustomResources {}
}
