import { defineModule } from "@wolfstar/kit";

/**
 * The Stars module: listing `@wolfstar/plugin-subcommands-advanced/module` in `modules` in `stars.config` registers
 * the subcommands plugin. The module itself takes no options; the package's behaviour is still configured through
 * `ClientOptions.subcommandsAdvanced` (for example `nameCommandsAutogenerated`).
 *
 * @example
 * ```ts
 * // stars.config.ts
 * export default defineConfig({
 *   modules: ['@wolfstar/plugin-subcommands-advanced/module'],
 * });
 * ```
 */
export default defineModule({
  meta: {
    name: "@wolfstar/plugin-subcommands-advanced",
    compatibility: { framework: ">=6.1.0" },
  },
  setup(options, ctx) {
    ctx.addPlugin({ from: "@wolfstar/plugin-subcommands-advanced/plugin", options });
  },
});
