import { Command as FrameworkCommand, container } from "@wolfstar/http-framework";
import {
  analyzeSubCommandParsed,
  analyzeSubcommandGroupParsed,
  parseSlashSubcommand,
} from "../utils/functions.js";
import { RegisterSubcommandsHooks } from "../utils/hooks.js";
import type { SubcommandCommandOptions } from "../utils/types.js";

export type AdvancedCommandOptions = FrameworkCommand.Options & SubcommandCommandOptions;

/**
 * Command class that can register itself as a modular subcommand (or grouped subcommand)
 * of a parent {@link Subcommand} / chat-input command.
 *
 * @example
 * ```typescript
 * import { Command } from '@wolfstar/plugin-subcommands-advanced';
 *
 * export class PingCommand extends Command {
 *   public constructor(context: Command.LoaderContext, options: Command.Options) {
 *     super(context, {
 *       ...options,
 *       registerSubCommand: {
 *         parentCommandName: 'utils',
 *         slashSubcommand: (builder) => builder.setName('ping').setDescription('Ping!')
 *       }
 *     });
 *   }
 *
 *   public override chatInputRun(interaction: Command.ChatInputInteraction) {
 *     return interaction.reply({ content: 'Pong!' });
 *   }
 * }
 * ```
 */
export class Command<
  Options extends AdvancedCommandOptions = AdvancedCommandOptions,
> extends FrameworkCommand<Options> {
  public constructor(context: FrameworkCommand.LoaderContext, options: Options = {} as Options) {
    const nameCommandsAutogenerated =
      container.client?.options.subcommandsAdvanced?.nameCommandsAutogenerated === true;
    let name = options.name;

    if (options.registerSubCommand && nameCommandsAutogenerated) {
      const parsed = parseSlashSubcommand(options.registerSubCommand.slashSubcommand);
      name = `${options.registerSubCommand.parentCommandName}/${parsed.name}`;
    }

    if (options.registerSubcommandInGroup && nameCommandsAutogenerated) {
      const parsed = parseSlashSubcommand(options.registerSubcommandInGroup.slashSubcommand);
      name = `${options.registerSubcommandInGroup.parentCommandName}/${options.registerSubcommandInGroup.groupName}/${parsed.name}`;
    }

    super(context, { ...options, name } as Options);

    if (this.options.registerSubCommand) {
      const { parentCommandName, slashSubcommand } = this.options.registerSubCommand;
      analyzeSubCommandParsed(this, parentCommandName, slashSubcommand);
    }

    if (this.options.registerSubcommandInGroup) {
      const { parentCommandName, groupName, slashSubcommand } =
        this.options.registerSubcommandInGroup;
      analyzeSubcommandGroupParsed(this, parentCommandName, groupName, slashSubcommand);
    }
  }
}

export namespace Command {
  export type Options = AdvancedCommandOptions;
  export type JSON = FrameworkCommand.JSON;
  /** @deprecated Use {@linkcode LoaderContext} instead. */
  export type Context = LoaderContext;
  export type LoaderContext = FrameworkCommand.LoaderContext;
  export type ChatInputInteraction = FrameworkCommand.ChatInputInteraction;
  export type AutocompleteInteraction = FrameworkCommand.AutocompleteInteraction;
  export type ApplicationCommandInteraction = FrameworkCommand.ApplicationCommandInteraction;
  export type Registry = FrameworkCommand.Registry;
}

/**
 * Parent command marker. Extend this for the chat-input command that owns modular
 * subcommands. Wiring of children is performed automatically by the plugin loader
 * strategy after all pieces are constructed.
 *
 * @example
 * ```typescript
 * import { RegisterCommand } from '@wolfstar/http-framework';
 * import { Subcommand } from '@wolfstar/plugin-subcommands-advanced';
 *
 * @RegisterCommand((builder) =>
 *   builder
 *     .setName('utils')
 *     .setDescription('Utility commands')
 *     .addSubcommandGroup((group) => group.setName('poll').setDescription('Polls'))
 * )
 * export class UtilsCommand extends Subcommand {}
 * ```
 */
export class Subcommand<
  Options extends FrameworkCommand.Options = FrameworkCommand.Options,
> extends FrameworkCommand<Options> {
  /**
   * Optional hooks for imperative {@link registerApplicationCommands} usage.
   */
  public readonly hooks = RegisterSubcommandsHooks;
}

export namespace Subcommand {
  export type Options = FrameworkCommand.Options;
  export type JSON = FrameworkCommand.JSON;
  /** @deprecated Use {@linkcode LoaderContext} instead. */
  export type Context = LoaderContext;
  export type LoaderContext = FrameworkCommand.LoaderContext;
  export type ChatInputInteraction = FrameworkCommand.ChatInputInteraction;
  export type AutocompleteInteraction = FrameworkCommand.AutocompleteInteraction;
  export type ApplicationCommandInteraction = FrameworkCommand.ApplicationCommandInteraction;
  export type Registry = FrameworkCommand.Registry;
}
