name: documentation

on:
    push:
        branches:
            - main
        tags:
            - 'v*'

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    docs:
        name: Documentation
        uses: wolfstar-project/.github/.github/workflows/reusable-documentation.yml@8fdfa590df5f28308ab35137b1dc39819ef70997 # main
        with:
            project-name: plugins
            docgen-command: pnpm exec typedoc --options typedoc.json --json docs-output/api.json
        secrets:
            WOLFSTAR_TOKEN: ${{ secrets.WOLFSTAR_TOKEN }}
